# Performs automated code review on pull requests and pushes to master/develop.

name: Code Review

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
