# Performs automated tests on pull requests and pushes to master/develop.

name: Automated testing

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: [12.x]
      - name: Install modules
        run: yarn install --frozen-lockfile
      # Run tests and provide coverage diff
      - name: TestCoverage
        id: testCovergae
        uses: anuraag016/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: false
